if (inTelegram) {
  document.getElementById('studioButton')?.addEventListener('click', openStudio);
  document.getElementById('supportForm')?.addEventListener('submit', sendSupport);
}
async function openStudio(){const r=await fetch('./api/studio',{headers:{'x-telegram-init-data':tg.initData}});if(r.status===403)return popup('Studio privé','Accès réservé au compte créateur de Pesce.');if(!r.ok)return popup('Studio indisponible','Réessayez dans un instant.');openSection('studio');loadStudio();}
async function sendSupport(e){e.preventDefault();const f=e.currentTarget,b=document.getElementById('supportSubmit'),s=document.getElementById('supportStatus'),m=f.querySelector('textarea')?.value.trim();if(!m)return;b.disabled=true;b.textContent='Envoi…';try{const r=await fetch('./api/support',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:m,initData:tg.initData})});const d=await r.json();if(!r.ok)throw Error(d.message||'Échec de l’envoi.');f.reset();s.textContent=`Demande ${d.ticketId} envoyée. Réponse dans Telegram.`;}catch(x){s.textContent=x.message;}finally{b.disabled=false;b.textContent='Envoyer la demande';}}
async function loadStudio(){const el=document.getElementById('studioFeed');if(!el)return;el.innerHTML='<article class="empty-card"><span>⏳</span><h3>Chargement…</h3></article>';try{const r=await fetch('./api/studio',{headers:{'x-telegram-init-data':tg.initData},cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.message||'Studio indisponible.');const t=d.totals||{};el.innerHTML=`<div class="studio-kpis"><article class="kpi-card"><small>Contenus</small><strong>${t.total||0}</strong><span>${t.text||0} textes</span></article><article class="kpi-card"><small>Photos</small><strong>${t.photo||0}</strong></article><article class="kpi-card"><small>Audios</small><strong>${t.audio||0}</strong></article><article class="kpi-card"><small>Étoiles</small><strong>${Number(d.stars||0).toLocaleString('fr-FR')} ⭐</strong><span>${d.supporters||0} soutien(s)</span></article></div><article class="studio-card"><p class="card-kicker">ASSISTANCE</p><h3>Demandes ouvertes <span class="count-badge">${d.openTickets||0}</span></h3>${(d.recentTickets||[]).map(x=>`<div class="ticket-card"><strong>${esc(x.id)}</strong><small>${esc(x.username?'@'+x.username:x.firstName||'Utilisateur')} · ${fmt(x.createdAt)}</small><p>${esc(x.message||'')}</p></div>`).join('')||'<p class="studio-muted">Aucune demande ouverte.</p>'}</article><article class="studio-card"><p class="card-kicker">SOUTIENS</p><h3>Derniers paiements</h3>${(d.recentPayments||[]).map(x=>`<div class="studio-row"><span>⭐ ${x.amount||0}</span><small>${esc(x.username?'@'+x.username:'Utilisateur')} · ${fmt(x.paidAt)}</small></div>`).join('')||'<p class="studio-muted">Aucun paiement.</p>'}</article>`;}catch(x){el.innerHTML=`<article class="empty-card"><span>⚠️</span><h3>Studio indisponible</h3><p>${esc(x.message)}</p></article>`;}}
function fmt(v){const d=v?new Date(v):null;return d&&!isNaN(d)?d.toLocaleString('fr-FR',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'}):'date inconnue';}
function esc(v){return String(v).replace(/[&<>\'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
